name: Build and Test Car Rental App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Ensure gradlew is executable
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Step 4: Build and test with Gradle
      - name: Build and test with Gradle
        run: ./gradlew build
